add civic_issues
sharlagelfand/opendatatoronto pull request #4
Opened 2019-08-29 03:04 UTC by sushmitavgopalan16

Hi Sharla! 
This is my first attempt at doing this - thank you in advance for your patience and thank you for putting the tweet out!
I think I've made the changes you described - I can render the README locally but the badges won't build - I'm assuming this is an issue with my pandoc installation. Does this work (and also is this how this works?)

2019-08-29 18:13 UTC, sharlagelfand requested changes
Thanks for doing this @sushmitavgopalan16! I've made a couple comments on things to fix but otherwise it looks good to me :) 

Just a note for the future, if you use a phrase like "closes #3" in the pull request, it will actually close the issue when the PR is merged. more info on that here: https://help.github.com/en/articles/closing-issues-using-keywords

2019-08-29 18:13 UTC, sharlagelfand commented on tests/testthat/test-list_packages.R
> +
can you please remove this extra white line?

2019-08-29 18:13 UTC, sharlagelfand commented on README.Rmd
> +packages <- list_packages(limit = 1000)
@HernanGaleano pointed out on #3 that `list_packages()` doesn't show the dataset unless you increase the `limit` (which I think you saw since you changed the `limit`). so i'm actually going to change the code to use `search_packages()` or `show_package()` for this example. would you mind changed `limit` back to 100?

2019-08-29 19:32 UTC, sushmitavgopalan16 commented
Hi Sharla! I made the changes. Let me know if you'd like me to change the example to search_package! 

I didn't know about the keywords thing - thanks for sharing!

2019-08-31 17:01 UTC, sharlagelfand commented
no worries, i need to make some other changes to the README and vignettes so i'll do that.

looks good to me now! congratulations on your first PR 🎉

2019-08-31 17:01 UTC, merged